### ISSUE TITLE
Develop the program further: UK or US English spelling?

### ISSUE THREAD

**Issue by emlala** [emlala/emmiagata#4]
Check notes.md for more information on the type of data we want!

**Comment by emlala** [comment]
Uploaded the file variation_finder.py, which contains the latest version of the program. It currently gives the output of: 
>Hello, please give me a word in US or UK English spelling: _input_
>x documents found with the word spelled only as _input_. This is the _US/UK_ version of the word.
>y documents found with the word spelled only as _other spelling_. This is the _US/UK_ version of the word.
>z documents found with mixed spelling.

**Comment by emlala** [comment]
Now we want the program to print an example list of articles with the different spellings, and also links to the current Wikipedia articles. 

NOTE! The articles used for searching can be dated and differ from the current state of the corresponding article that can be found online. The data is from the beginning of November and Wikipedia articles can be edited at any time.

**Comment by DmitryKey** [comment]
Hello,

Can you please upload 'wordlist.csv' to your repo.

**Comment by emlala** [comment]
Done!
